CREATE TABLE public.slots (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL,
  provider text,
  icon_url text,
  default_bet numeric(12,2),
  default_buyin numeric(12,2),
  created_at timestamptz NOT NULL DEFAULT now()
);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.slots TO anon, authenticated;
GRANT ALL ON public.slots TO service_role;
ALTER TABLE public.slots ENABLE ROW LEVEL SECURITY;
CREATE POLICY "slots public read" ON public.slots FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "slots public write" ON public.slots FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

CREATE TABLE public.hunts (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  number integer GENERATED BY DEFAULT AS IDENTITY,
  name text NOT NULL DEFAULT 'Bonus Hunt',
  channel text NOT NULL DEFAULT 'mkn',
  status text NOT NULL DEFAULT 'draft',
  target_bonuses integer DEFAULT 50,
  started_at timestamptz,
  ended_at timestamptz,
  show_last_bonus boolean NOT NULL DEFAULT true,
  big_win_alerts boolean NOT NULL DEFAULT true,
  overlay_position text NOT NULL DEFAULT 'right-center',
  created_at timestamptz NOT NULL DEFAULT now()
);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.hunts TO anon, authenticated;
GRANT ALL ON public.hunts TO service_role;
ALTER TABLE public.hunts ENABLE ROW LEVEL SECURITY;
CREATE POLICY "hunts public read" ON public.hunts FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "hunts public write" ON public.hunts FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

CREATE TABLE public.bonuses (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  hunt_id uuid NOT NULL REFERENCES public.hunts(id) ON DELETE CASCADE,
  slot_id uuid REFERENCES public.slots(id) ON DELETE SET NULL,
  slot_name text NOT NULL,
  sequence integer NOT NULL DEFAULT 1,
  buyin numeric(12,2) NOT NULL DEFAULT 0,
  bet numeric(12,2) NOT NULL DEFAULT 0,
  win numeric(12,2) NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX bonuses_hunt_idx ON public.bonuses (hunt_id, sequence);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.bonuses TO anon, authenticated;
GRANT ALL ON public.bonuses TO service_role;
ALTER TABLE public.bonuses ENABLE ROW LEVEL SECURITY;
CREATE POLICY "bonuses public read" ON public.bonuses FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "bonuses public write" ON public.bonuses FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

CREATE OR REPLACE FUNCTION public.touch_updated_at() RETURNS trigger
LANGUAGE plpgsql SET search_path = public AS $$
BEGIN NEW.updated_at = now(); RETURN NEW; END; $$;
CREATE TRIGGER bonuses_touch BEFORE UPDATE ON public.bonuses
FOR EACH ROW EXECUTE FUNCTION public.touch_updated_at();

ALTER TABLE public.hunts REPLICA IDENTITY FULL;
ALTER TABLE public.bonuses REPLICA IDENTITY FULL;
ALTER PUBLICATION supabase_realtime ADD TABLE public.hunts;
ALTER PUBLICATION supabase_realtime ADD TABLE public.bonuses;

INSERT INTO public.slots (name, provider, default_bet, default_buyin) VALUES
('Gates of Olympus','Pragmatic Play',2.00,200.00),
('Sweet Bonanza','Pragmatic Play',2.00,200.00),
('Sugar Rush 1000','Pragmatic Play',2.00,200.00),
('Starlight Princess','Pragmatic Play',2.00,200.00),
('Big Bass Splash','Pragmatic Play',2.00,200.00),
('Wanted Dead or a Wild','Hacksaw Gaming',2.00,200.00),
('Le Bandit','Hacksaw Gaming',2.00,200.00),
('Chaos Crew 2','Hacksaw Gaming',2.00,200.00),
('San Quentin xWays','Nolimit City',2.00,200.00),
('Mental','Nolimit City',2.00,400.00),
('Fire in the Hole 2','Nolimit City',2.00,400.00),
('Book of Dead','Play''n GO',2.00,0.00),
('Money Train 4','Relax Gaming',2.00,200.00),
('Dead or Alive 2','NetEnt',2.00,0.00),
('Razor Shark','Push Gaming',2.00,200.00);